# Generated by Django 6.0.3 on 2026-09-18 18:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('BANK_ACCOUNT', 'Bank Account'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('INVESTMENT', 'Investment'), ('OTHER', 'Other')], default='BANK_ACCOUNT', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='RS', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='households.household')),
            ],
            options={
                'verbose_name': 'Financial Account',
                'verbose_name_plural': 'Financial Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_memberships', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.financialaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'user'), name='unique_account_user_membership')],
            },
        ),
    ]
